//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLS.DesignLibrary.Calculations.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OutputTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OutputTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TLS.DesignLibrary.Calculations.Properties.OutputTemplates", typeof(OutputTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///  &lt;h1&gt;
        ///  Bolt Resistances
        ///&lt;/h1&gt;
        ///  &lt;h2&gt;Properties&lt;/h2&gt;
        ///  &lt;h3&gt;Bolt Properties&lt;/h3&gt;
        ///  &lt;table&gt;
        ///    &lt;input name=&quot;Diameter&quot;/&gt;
        ///    &lt;input name=&quot;HoleDiameter&quot;/&gt;
        ///    &lt;input name=&quot;Grade&quot;/&gt;
        ///	&lt;input name=&quot;DesignUltimateStrength&quot;/&gt;
        ///	&lt;input name=&quot;TensileStressArea&quot;/&gt;
        ///    &lt;input name=&quot;PartialFactorResistanceBolt&quot;/&gt;
        ///	&lt;input name=&quot;MajorSpacing&quot;/&gt;
        ///	&lt;input name=&quot;MinorSpacing&quot;/&gt;
        ///  &lt;/table&gt;
        ///  &lt;h3&gt;Member 1 Properties&lt;/h3&gt;
        ///  &lt;table&gt;
        ///    &lt;input name=&quot;Member1Thickness&quot;/&gt;
        ///    &lt;input name=&quot;Member1UltimateStre [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataTypes_Bolt {
            get {
                return ResourceManager.GetString("DataTypes_Bolt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DataTypes_BoltGroup {
            get {
                return ResourceManager.GetString("DataTypes_BoltGroup", resourceCulture);
            }
        }
    }
}
